PayCloud.WebApp/Controllers/ContactFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PayCloud.Services.Providers;
using PayCloud.WebApp.Models;

namespace PayCloud.WebApp.Controllers
{
    public class ContactFormController : Controller
    {
        private readonly IDateTimeNowProvider dateTimeNowProvider;
        private readonly IEmailSender emailSender;
        private readonly IFileServicesProvider fileServicesProvider;

        public ContactFormController(IDateTimeNowProvider dateTimeNowProvider,
            IEmailSender emailSender,
            IFileServicesProvider fileServicesProvider)
        {
            this.dateTimeNowProvider = dateTimeNowProvider ?? throw new ArgumentNullException(nameof(dateTimeNowProvider));
            this.emailSender = emailSender ?? throw new ArgumentNullException(nameof(emailSender));
            this.fileServicesProvider = fileServicesProvider ?? throw new ArgumentNullException(nameof(fileServicesProvider));
        }

        // GET: ContactForm/GetAboutAppPartial
        public ActionResult GetAboutAppPartial()
        {
            return this.PartialView("_About");
        }

        // GET: ContactForm/SendUserMessage
        public ActionResult GetUserMessagePartialView()
        {
            return this.PartialView("_SendUserMessagePartial");
        }

        // POST: ContactForm/SendUserMessage
        [HttpPost]
        public ActionResult SendUserMessage(ContactFormDto contactFormDto)
        {
            string fileContent;
            const string filePath = "UserMessagesLog.txt";
            try
            {
                // TODO: Send and email
                if (string.IsNullOrWhiteSpace(contactFormDto?.Title)
                    && string.IsNullOrWhiteSpace(contactFormDto?.Message)
                    && string.IsNullOrWhiteSpace(contactFormDto?.Name)
                    && string.IsNullOrWhiteSpace(contactFormDto?.Email))
                {
                    return this.Json("Message not sent, because there wasn't any message.");
                }
                else
                {
                    fileContent = $"Time: {this.dateTimeNowProvider.Now.ToString()}\nName: {contactFormDto?.Name?.Trim()}\nEmail: {contactFormDto?.Email?.Trim()}\nTitle: {contactFormDto?.Title?.Trim()}\nMessage: {contactFormDto?.Message?.Trim()}";
                    this.fileServicesProvider.WriteToTextFile(filePath, fileContent);
                }
            }
            catch
            {
                return this.Json("Message not sent, because the system is busy. Please, try again later.");
            }
            try
            {
                string fromEmail = "cloud.team.public.relations@gmail.com";
                string ccEmail = "";
                string bccEmail = "cloud.team.public.relations@gmail.com";
                this.emailSender.SendMail(
                    contactFormDto.Email,
                    fromEmail,
                    ccEmail,
                    bccEmail,
                    $"New pay cloud user's message {this.dateTimeNowProvider.Now.ToString()}",
                    fileContent);
                this.fileServicesProvider.WriteToTextFile(filePath, "\n\n");
                return this.Json("");
            }
            catch (Exception)
            {
                this.fileServicesProvider.WriteToTextFile(filePath, "ERROR: Email not sent!\n\n");
                return this.Json("");
            }
        }
    }
}

PayCloud.WebApp/Views/ContactForm/SendUserMessage.cshtml
@model ContactFormDto

<div class="card-body">
    <h4 class="my-4 text-center text-uppercase">Share your opinon with us</h4>
    <form asp-controller="ContactForm" asp-action="SendUserMessage" method="post" style="width:500px">
        <div class="input-item">
            <label for="Name">Name</label>
            <input asp-for=Name id="InputName" type="text" value="" placeholder="Enter name" class="form-control" required>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="input-item">
            <label for="Title">Title</label>
            <input asp-for=Title id="InputTitle" type="text" value="" placeholder="Enter title" class="form-control" required>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <br />
        <div class="input-item">
            <label for="Message">Message</label>
            <div>
                <textarea id="InputMessage" name="Message" cols="60" rows="5" runat="server"></textarea>
            </div>
            @*<input asp-for=Message id="InputMessage" type="text" value="" placeholder="Enter message" class="form-control" required>
            <span asp-validation-for="Message" class="text-danger"></span>*@
        </div>
        <div class="input-item">
            <label for="Email">Email</label>
            <input asp-for=Email id="InputEmail" type="text" value="" placeholder="Enter email" class="form-control" required>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div>
            <br />
            <button type="submit" class="btn btn-default btn-block">Submit</button>
        </div>
    </form>
</div>