PayCloud.WebApp/Areas/User/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Mvc;
using PayCloud.Services;
using PayCloud.Services.Dto;
using PayCloud.Services.Identity.Contracts;
using PayCloud.Services.Utils;
using PayCloud.WebApp.Areas.User.Models.AccountViewModels;
using PayCloud.WebApp.Mappers;
using PayCloud.WebApp.Utils;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PayCloud.WebApp.Areas.User.Controllers
{
    [Area("User")]
    [JWTAuthorizeAttribute("User")]
    public class AccountsController : Controller
    {
        private readonly IAccountService accountService;
        private readonly IClientService clientService;
        private readonly IAuthorizationService authorizationService;
        private readonly IViewModelMapper<AccountDto, UserAccountViewModel> accountMapper;

        public AccountsController(
            IAccountService accountService,
            IClientService clientService,
            IAuthorizationService authorizationService,
            IViewModelMapper<AccountDto, UserAccountViewModel> accountMapper)
        {
            this.accountService = accountService ?? throw new ArgumentNullException(nameof(accountService));
            this.clientService = clientService ?? throw new ArgumentNullException(nameof(clientService));
            this.authorizationService = authorizationService ?? throw new ArgumentNullException(nameof(authorizationService));
            this.accountMapper = accountMapper ?? throw new ArgumentNullException(nameof(accountMapper));
        }

        // GET: User/Accounts

        public async Task<IActionResult> Index()
        {
            this.ViewData["Title"] = "ACCOUNTS";
            return this.View();
        }

        public async Task<IActionResult> GetAccountsList(
                    string sortOrder,
                    string currentFilter,
                    int? clientId,
                    int? pageNumber,
                    int? pageSize)
        {
            this.ViewData["AccNumSortParm"] = (string.IsNullOrEmpty(sortOrder) || sortOrder == "AccountNumber") ? "AccountNumber_desc" : "AccountNumber";
            this.ViewData["BalanceSortParm"] = sortOrder == "Balance" ? "Balance_desc" : "Balance";
            this.ViewData["NickNameSortParm"] = sortOrder == "NickName" ? "NickName_desc" : "NickName";
            this.ViewData["ClientNameSortParm"] = sortOrder == "ClientName" ? "ClientName_desc" : "ClientName";
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["LengthOptions"] = new int[] { 5, 10, 15, 20 };

            this.ViewData["CurrentFilter"] = currentFilter;
            this.ViewData["ClientId"] = clientId;

            if (pageSize == null)
            {
                pageSize = 5;
            }
            this.ViewData["pageSize"] = pageSize;

            var pageIndex = pageNumber ?? 1;

            var userId = this.authorizationService.GetLoggedUserId();

            var accounts = await this.accountService.GetAllUserAccountsAsync(userId, (pageIndex - 1) * (int)pageSize, (int)pageSize, currentFilter, clientId, sortOrder);
            var accountsCount = await this.accountService.GetUserAcountsCountAsync(userId, currentFilter, clientId);

            var accountViewModelList = accounts.Select(this.accountMapper.MapFrom);
            var result = PaginatedList<UserAccountViewModel>.Create(accountViewModelList, accountsCount, pageIndex, (int)pageSize, true);

            return this.PartialView("_UserAccountsListPartial", result);
        }

        public async Task<IActionResult> GetPieChartInfo()
        {
            var userId = this.authorizationService.GetLoggedUserId();

            var accounts = await this.accountService.GetAccountsForPieAsync(userId);
            return this.Json(accounts);
        }


        public async Task<IActionResult> GetLineChartInfo(int accountId)
        {
            var result = await accountService.LineChartInfo(accountId, 7);
            var formatedResult = result.Select(
                x => new
                {
                    Date = x.Date.ToString(format:"dd.MM"),
                    Balance = x.Balance
                });
            return this.Json(formatedResult);
        }

        // GET: Products list JSON for AJAX
        public async Task<IActionResult> AllAccountsList(string term)
        {
            return this.Json(await this.accountService.GetAllAccountsAsync(0, 5, contains: term));
        }

        // GET: Products list JSON for AJAX
        public async Task<IActionResult> UserAccountsList(string term)
        {
            var userId = this.authorizationService.GetLoggedUserId();

            return this.Json(await this.accountService.GetAllAccountsAsync(0, 5, contains: term, addBalance: true, userId: userId));
        }

        public async Task<IActionResult> AccountDetails(int accountId)
        {
            var accountDto = await accountService.GetAccountByIdAsync(accountId);
            var userId = this.authorizationService.GetLoggedUserId();

            accountDto.NickName = await accountService.GetAccountNicknameAsync(accountId, userId);
            return this.PartialView("_AccountDetailsPartial", accountMapper.MapFrom(accountDto));
        }

        [HttpGet]
        public async Task<IActionResult> ChangeNickname(int accountId)
        {
            var userId = this.authorizationService.GetLoggedUserId();
            var nicknameVieModel = new AccountNickname()
            {
                Nickname = await accountService.GetAccountNicknameAsync(accountId, userId),
                AccountId = accountId
            };

            return this.PartialView("_NicknamePartial",nicknameVieModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeNickname([FromBody]AccountNickname accountNickname)
        {
            try
            {
                var userId = this.authorizationService.GetLoggedUserId();
                await this.accountService.ChangeNicknameAsync(accountNickname.AccountId, userId, accountNickname.Nickname);
                return this.Ok(Json(string.Format(Constants.NicknameChanged,accountNickname.Nickname)));
            }
            catch (ServiceErrorException ex)
            {
                return this.BadRequest(this.Json(ex.Message));
            }
            catch (Exception)
            {
                return this.BadRequest(this.Json(Constants.CommonError));
            }

        }

    }
}

PayCloud.WebApp/Areas/User/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PayCloud.Services.Identity.Contracts;
using PayCloud.WebApp.Models;
using System;
using System.Threading.Tasks;

namespace PayCloud.WebApp.Areas.User.Controllers
{
    [Area("User")]
    public class IdentityController : Controller
    {
        private readonly ITokenManager tokenManager;
        private readonly IUserService userService;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly ICookieManager cookieManager;

        public IdentityController(
            IUserService userService,
            ITokenManager tokenManager,
            IHttpContextAccessor httpContextAccessor,
            ICookieManager cookieManager)
        {
            this.userService = userService;
            this.tokenManager = tokenManager;
            this.httpContextAccessor = httpContextAccessor;
            this.cookieManager = cookieManager;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel userModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(userModel);
                }

                var user = await userService.GetUserAsync(userModel.Username, userModel.Password);

                var token = tokenManager.GenerateToken(user.Username, user.Role, user.UserId.ToString());

                cookieManager.AddSessionCookieForToken(token, user.Username);

                if (user.Role == "User")
                {
                    return RedirectToAction("Index", "Accounts", new { area = "User" });
                }
                else
                {
                    return RedirectToAction("AdminLogin");

                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home", new { errorMessage = ex.Message });

                //return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            try
            {
                cookieManager.DeleteSessionCookies();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

PayCloud.WebApp/Areas/User/Views/Shared/_AccountDetailsPartial.cshtml
@model UserAccountViewModel


<partial name="_LineChartPartial" />


<div class="card mb-4">
    <div class="card-header">Account Details</div>
    <div class="card-body">
        <form class="form-horizontal row mt-2">

            <div class="col-xl-12 col-lg-12  col-sm-12">
                <div class="form-group">
                    <dl class="row">
                        <dt class="col-xl-3 col-lg-4 col-sm-12">
                            @Html.DisplayNameFor(model => model.NickName)
                        </dt>
                        <dd class="col-xl-9 col-lg-8 col-sm-12">
                            @Html.DisplayFor(model => model.NickName)
                        </dd>
                        <dt class="col-xl-3 col-lg-4 col-sm-12">
                            @Html.DisplayNameFor(model => model.AccountNumber)
                        </dt>
                        <dd class="col-xl-9 col-lg-8 col-sm-12">
                            @Html.DisplayFor(model => model.AccountNumber)
                        </dd>
                        <dt class="col-xl-3 col-lg-4 col-sm-12">
                            @Html.DisplayNameFor(model => model.Balance)
                        </dt>
                        <dd class="col-xl-9 col-lg-8 col-sm-12">
                            @Html.DisplayFor(model => model.Balance)
                        </dd>
                        <dt class="col-xl-3 col-lg-4 col-sm-12">
                            @Html.DisplayNameFor(model => model.ClientName)
                        </dt>
                        <dd class="col-xl-9 col-lg-8 col-sm-12">
                            @Html.DisplayFor(model => model.ClientName)
                        </dd>
                    </dl>

                </div>
            </div>
        </form>
    </div>
</div>

PayCloud.WebApp/Areas/User/Views/Shared/_LineChartPartial.cshtml
<div class="col-12">
    <div class="card mb-4">
        <div class="card-header">Account Analytics</div>
        <div class="card-body">
            <canvas id="myAreaChart" width="100%" height="50"></canvas>
        </div>
    </div>
</div>

PayCloud.WebApp/Areas/User/Views/Shared/_MakePaymentPartial.cshtml
@model UserAccountViewModel

<div class="card mb-4">
    <div class="card-header">Make payment</div>
    <div class="card-body">
        <div class="col-xl-12 col-lg-12  col-sm-12">

        </div>
        <form class="form-horizontal row mt-2" id="create-payment-form" asp-area="User" asp-controller="Accounts">
            <div class="col-xl-12 col-lg-12  col-sm-12">
                <div class="form-group">
                    <label>Sender account</label>
                    @if (Model != null)
                    {
                        <input type="text" class="form-control" value="@($"{Model.ClientName}: {Model.AccountNumber} (balance: {Model.Balance})")" id="senderaccount" data-senderaccount="@(Model.AccountId)" data-balance="@Model.Balance" disabled>
                    }
                    else
                    {
                        <select class="js-data-example-ajax" id="senderaccount" data-senderaccount="" data-balance=""></select>
                    }
                </div>
                <div class="form-group">
                    <label>Payment amount</label>
                    <input type="number" class="form-control" placeholder="Enter amount" value="" ID="paymentAmount" data-amount="" required autofocus="">
                </div>
                <div class="form-group">
                    <label>Receiver account</label>
                    <select class="js-data-example-ajax" id="receiveraccount" data-receiveraccount=""></select>
                </div>
                <div class="form-group">
                    <label>Payment description</label>
                    <input type="text" class="form-control" id="paymentDescription">
                </div>
            </div>
            <div class="col-6 text-left">

                <button type="button" class="btn btn-default mt-2" onclick="savePayment()">Save Payment</button>
            </div>
            <div class="col-6 text-right">
                <button type="button" class="btn btn-default mt-2 ld-ext-right" id="make-payment-button" onclick="makePayment()">
                    <div class="ld ld-ring ld-spin"></div>
                    Make Payment
                </button>
            </div>
        </form>
    </div>
</div>


PayCloud.WebApp/Areas/User/Views/Shared/_MyDialogModal.cshtml
<div class="modal fade" id="myDialogModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myDialogModal-title"></h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body"  id="myDialogModal-main"></div>
            <div class="modal-footer">
                <button class="btn btn-primary"  id="myDialogModal-button1">Pay</button>
                <button class="btn btn-primary"  id="myDialogModal-button2">Dismiss</button>
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

PayCloud.WebApp/Areas/User/Views/Shared/_NicknamePartial.cshtml
@model AccountNickname

<div class="card mb-4">
    <div class="card-header"></div>
    <div class="card-body">
        <form class="form-horizontal row mt-2">

            <div class="col-xl-12 col-lg-12  col-sm-12">
                <div class="form-group">
                    <label>Balance</label>
                    <input type="text" class="form-control" value="@Model.Nickname" ID="nickname-input" required autofocus="">
                </div>
            </div>
            <div class="col-12 text-right">
                <button type="button" class="btn btn-default mt-2" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-default mt-2" onclick="changeNickname(@Model.AccountId)">&nbsp;Save&nbsp;</button>
            </div>
        </form>
    </div>
</div>

PayCloud.WebApp/Areas/User/Views/Shared/_PieChartPartial.cshtml

        <div class="card mb-4">
            <div class="card-header text_md_center">My accounts chart</div>
            <div class="card-body">
                <canvas id="myPieChart" width="80%" height="111"></canvas>
            </div>
        </div>

@section Scripts {

    <script>

    </script>
    }

PayCloud.WebApp/Areas/User/Views/Shared/_SideNavPartial.cshtml
  <!-- Navigation UP-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="index">
        <img class="logo_icon" src="/images/logo_icon.png">
        <img class="logo" src="/images/dashboard_logo.png">
    </a>
    <div class="mobile_menu">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-menu icons"></span>
        </button>
        <a href="/" class="navbar-toggler" data-toggle="collapse" data-target="#navbarheader" aria-controls="navbarheader" aria-expanded="false" aria-label="Toggle navigation"><i class="icon-options-vertical"></i></a>
    </div>
    <div class="collapse navbar-collapse" id="navbarheader">
        <ul class="navbar-nav">
            <li class="nav-item d-none d-lg-block">
                <a class="nav-link text-center menubar" id="sidenavToggler">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                </a>
            </li>
            <li class="nav-item">
                <a href="javascript:void(0)/index.html" class="search_icon"><i class="fa fa-search"></i></a>
                <form class="form-inline search_input">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Search for...">
                        <span class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
            </li>
        </ul>
        <partial name="_UserBannerPartial">
    </div>

    <!-- Navigation SIDE-->
    <div class="collapse navbar-collapse navbar-sidenav fc-scroll" id="navbarResponsive">
        <ul class="navbar-nav" id="exampleAccordion">
            <li class="nav-item active" id="menu-item1">
                <a class="nav-link" href="/user/accounts" onclick="return menuClick('menu-item1');">
                    <i class="icon-wallet icons"></i>
                    <span class="nav-link-text">Accounts</span>
                </a>
            </li>
            <li class="nav-item" id="menu-item2">
                <a class="nav-link" href="/user/transactions" onclick="return menuClick('menu-item2');">
                    <i class="icon-shuffle icons"></i>
                    <span class="nav-link-text">Transactions</span>
                </a>
            </li>
           
        </ul>
    </div>

</nav>

PayCloud.WebApp/Areas/User/Views/Shared/_UILayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content>
    <meta name="author" content>
    <title>@ViewData["Title"] - PayCloud</title>
    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="../assets/images/favicon.png">
    <!-- Bootstrap core CSS-->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Google Font -->
    <!-- Icon Fonts-->
    <link href="/vendor/webfont/css/cryptocoins.css" rel="stylesheet" type="text/css">
    <link href="/vendor/webfont/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="/css/admin.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" rel="stylesheet">

    <!-- Toastr-->
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">*@
    <link rel="stylesheet" href="~/css/toastr.min.css">
    <!-- JQuery UI css-->
    <link rel="stylesheet" href="~/jquery-ui-1.12.1/jquery-ui.min.css">
    <!-- Custom styles for project-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/loading.css" />
    <link rel="stylesheet" href="~/css/loading-btn.css" />

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="fixed-nav sticky-footer" id="page-top">
    <div class="bg_image h-100">
        <span class="AntiForge"> @Html.AntiForgeryToken() </span>
        <partial name="_SideNavPartial" />

        <div class="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <div class="mouse-hover-tooltip" data-toggle="tooltip" data-placement="top" title="Leave a message for us">
                        <a id="leave-us-a-message-id" onclick="GetMessageModal()" href="#leave-us-a-message-id">
                            <div>
                                <img src="~/images/write_a_message_icon.png" alt="Email:" style="width:30px;height:30px" />
                                <small>Leave a message</small>
                            </div>
                        </a>
                    </div>
                    @*<div class="mouse-hover-tooltip" data-toggle="tooltip" data-placement="top" title="Click to copy our email address">
                        <a id="send-us-a-message-id" onclick="copyToClipboard('our-email-address')" href="#send-us-a-message-id">
                            <div>
                                <img src="~/images/Email_icon.svg" alt="Email:" style="width:30px;height:30px" />
                                <small id="our-email-address">cloud.team.public.relations@gmail.com</small>
                            </div>
                        </a>
                    </div>*@
                    <small>© 2019 Telerik Academy.</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded btn-default" onclick="window.scrollTo(0, 0);">
            <i class="fa fa-angle-up"></i>
        </a>
    </div>

    <!-- Leave a message for us modal -->
    <div id="myModalPartial" style="width:200px">
        <partial name="_ModalPartial" />
    </div>

    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Do you want to end your current session...</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href='@Url.Action("Logout","Identity")' onclick="userRemoveSessionSelect();">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <partial name="_MyDialogModal" />
    <!-- Bootstrap core JavaScript-->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Page level plugin JavaScript-->
    <script src="/vendor/chart.js/Chart.min.js"></script>
    <script src="/vendor/datatables/jquery.dataTables.js"></script>
    <script src="/vendor/datatables/dataTables.bootstrap4.js"></script>
    <!--Perfect scrollbar.js-->
    <script src="/js/perfect-scrollbar.js"></script>
    <!-- countdown js  -->
    <script src="/js/jquery.countdown.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="/js/admin.js"></script>
    <!-- Custom scripts for this page-->
    <script src="/js/admin-datatables.min.js"></script>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>*@
    <!-- Toastr-->
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>*@
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/toastrOptions.js"></script>

    <!-- JQuery UI-->
    <script src="~/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script src="~/js/userMenu.js"></script>

    <script>
        function isNullOrWhitespace(input) {
            return !input || !input.trim() || "" === input.trim();
        }

        $('#mymodal-close-button').click(function (event) {
            //event.preventDefault();
            //event.stopImmediatePropagation();
            let tempName = $('#InputName').val();
            let tempTitle = $('#InputTitle').val();
            let tempEmail = $('#InputEmail').val();
            let tempMessage = $('#InputMessage').val();

            url = '/ContactForm/SendUserMessage';
            sendUsAMessagePost(url, tempName, tempTitle, tempEmail, tempMessage);
        });

        function sendUsAMessagePost(url, tempName, tempTitle, tempEmail, tempMessage) {
            $("#myModal").modal('hide');
            if (url == null) {
                url = '/ContactForm/SendUserMessage';
            }
            $.ajax({
                url: url,
                data: {
                    Name: tempName,
                    Title: tempTitle,
                    Email: tempEmail,
                    Message: tempMessage
                },
                type: "post",
                success: function (data) {
                    if (isNullOrWhitespace("" + data)) {
                        toastr.success('Message sent successfully');
                    }
                    else {
                        toastr.error("" + data);
                    }
                },
                error: function (xhr) {
                    console.log(xhr);
                    toastr.error('Message not sent, please try later.');
                }
            });
        }

        function getAboutAppPartialFromController() {
            let url = '/ContactForm/GetAboutAppPartial';
            console.log(url);

            $('#mymodaltitle').text('We value your ideas')
            $('#myModalSize').attr('class', 'modal-dialog-cust-mid');

            $("#mymodalmain").html('<div class="center"><img src="/images/loading.gif" alt="Loading..."></div>');
            SentMessageDataToController(url, 'mymodalmain');
            $("#mymodal-close-button").toggle(true);

            $("#myModal").modal('show');

            sendUsAMessagePost(url, 'mymodal');
        };

        function SentMessageDataToController(url, elementid) {

            if (url == null) {

                url = '/ContactForm/GetUserMessagePartialView';
            }
            if (elementid == null) {
                elementid = 'mymodalmain';
            }
            $.ajax({
                url: url,
                type: "get",
                success: function (data) {
                    $('#' + elementid).html(data);
                },
                error: function (xhr) {
                    console.log(xhr);
                    $('#' + elementid).html('Error loading clients list...');
                }
            });
        }

        function GetMessageModal() {
            $('#mymodaltitle').text('We value your ideas')
            $('#myModalSize').attr('class', 'modal-dialog-cust-mid');

            let url = '/ContactForm/GetUserMessagePartialView';
            console.log(url);
            $("#mymodalmain").html('<div class="center"><img src="/images/loading.gif" alt="Loading..."></div>');
            SentMessageDataToController(url, 'mymodalmain');
            $("#mymodal-close-button").toggle(true);

            $("#myModal").modal('show');
        };

        function copyToClipboard(elementId) {
            // Create a "hidden" input
            var aux = document.createElement("input");
            // Assign it the value of the specified element
            aux.setAttribute("value", document.getElementById(elementId).innerHTML);
            // Append it to the body
            document.body.appendChild(aux);
            // Highlight its content
            aux.select();
            // Copy the highlighted text
            document.execCommand("copy");
            // Remove it from the body
            document.body.removeChild(aux);
            toastr.success("Our email address is copied to the clipboard");
        }

    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

PayCloud.WebApp/Areas/User/Views/Shared/_UserBannerPartial.cshtml
@using PayCloud.Services.Identity.Contracts

@inject IUserService userService

<ul class="navbar-nav ml-auto align-items-center">
    <li class="nav-item dropdown menu_user">
        <a class="nav-link dropdown-toggle" id="userDropdown" href="#/index.html" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Logged in as @((await userService.GetLoggedUserAsync()).Name)
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <ul class="menu-nav list_none">
                <li><a href=""><i class="icon-user"></i><span>My Profile</span></a></li>
                <li><div class="dropdown-divider"></div></li>
                <li><a href="#/index.html" data-toggle="modal" data-target="#exampleModal"><i class="icon-logout icons"></i>Logout</a></li>
            </ul>
        </div>
    </li>
</ul>